#!/usr/bin/env python
# -*- coding: utf-8 -*-

import anndata
import numpy as np
import scipy.sparse as sp
import os


def generate_poisson_technoise_files(file_path, output_dir):
    """
    Resample via Poisson to simulate sequencing technical noise (shot noise).

    Technical noise simulator:
      - Assume the current expression matrix contains ideal expected counts lambda0_ij
        (or proportional to them).
      - For a given depth factor d, define lambda_ij = d * lambda0_ij.
      - Then resample observed counts via:
            X_ij ~ Poisson(lambda_ij)

    This captures sequencing as a random sampling process with Poisson shot noise:
    Var(X_ij) = E[X_ij] = lambda_ij, so lowly expressed genes have higher relative noise.
    """

    os.makedirs(output_dir, exist_ok=True)
    print(f"--- Output directory ready: {output_dir} ---")

    print(f"--- Loading data: {file_path} ---")
    adata_original = anndata.read_h5ad(file_path)

    print("\n--- Original data layout ---")
    print(adata_original)

    is_sparse = sp.issparse(adata_original.X)
    print(f"\nexpression matrix (adata.X) is sparse: {is_sparse}")

    original_data = adata_original.X.toarray() if is_sparse else adata_original.X.copy()
    original_data = np.maximum(original_data, 0.0)

    depth_factors = [0.25, 0.5, 1.0, 2.0, 4.0]
    print(f"\n--- Sequencing depth factors: {depth_factors} ---")

    n_cells, n_genes = original_data.shape
    base_filename = os.path.splitext(os.path.basename(file_path))[0]

    for depth in depth_factors:
        print(f"\n========== Processing technical noise level: depth = {depth} ==========")

        lam = original_data * depth
        lam = np.maximum(lam, 0.0)

        print("--- Poisson resampling from current lambda matrix ---")
        noisy_counts = np.random.poisson(lam=lam).astype(np.float32)

        adata_noisy = anndata.AnnData(
            noisy_counts,
            obs=adata_original.obs.copy(),
            var=adata_original.var.copy()
        )

        adata_noisy.uns["technoise_model"] = "Poisson_resampling"
        adata_noisy.uns["technoise_depth_factor"] = float(depth)
        adata_noisy.uns["technoise_note"] = (
            "Counts generated by Poisson resampling with lambda_ij = depth * original_ij "
            "to simulate sequencing shot noise."
        )

        output_filename = f"{base_filename}_poisson_depth_{depth}.h5ad"
        output_path = os.path.join(output_dir, output_filename)
        print(f"Saving to: {output_path}")
        adata_noisy.write_h5ad(output_path)

    print("\n--- All Poisson technical noise datasets generated ---")


if __name__ == "__main__":
    input_file = "/share/PertBench/data/fig1/raw_task1/task1_train_CD4T_exp.h5ad"

    if not os.path.exists(input_file):
        print(f"Not found '{input_file}'. Creating dummy h5ad for testing...")
        n_obs, n_vars = 100, 500
        X_dummy = np.random.poisson(lam=5.0, size=(n_obs, n_vars)).astype(np.float32)
        dummy_adata = anndata.AnnData(X_dummy)
        dummy_adata.write(input_file)
        print(f"Created dummy file '{input_file}'.")

    output_directory = "/share/PertBench/data/add_poisson_technoise_output"

    generate_poisson_technoise_files(input_file, output_directory)
