#!/usr/bin/env python
# -*- coding: utf-8 -*-

import anndata
import numpy as np
import scipy.sparse as sp
import os


def generate_poisson_technoise_files(file_path, output_dir):
    """
     using Poisson noise (shot noise).

    Technical noise simulator:
      - Assume the current expression matrix contains ideal expected counts λ0_ij
        (or proportional to them).
      - For a given depth factor d, define λ_ij = d * λ0_ij.
      - Then resample observed counts via:
            X_ij ~ Poisson(λ_ij)

    This captures the idea that sequencing is a random sampling process with
    Poisson shot noise: Var(X_ij) = E[X_ij] = λ_ij, so lowly expressed genes
    have higher relative noise.
    """

    # 1. Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    print(f"--- Output directory: {output_dir} ---")

    # 2. Load original h5ad file
    print(f"--- Loadingdata: {file_path} ---")
    adata_original = anndata.read_h5ad(file_path)

    print("\n--- originaldata under ---")
    print(adata_original)

    is_sparse = sp.issparse(adata_original.X)
    print(f"\nexpressedmatrix (adata.X) whetherassparse matrix: {is_sparse}")

    # Convert to dense array if necessary
    # NOTE: For very large data, this may be memory-heavy.
    original_data = adata_original.X.toarray() if is_sparse else adata_original.X.copy()

    # Enforce non-negativity: Poisson rates must be >= 0
    original_data = np.maximum(original_data, 0.0)

    # 3. Define different "sequencing depth" factors to control technical noise level
    #    Smaller depth => lower counts => higher relative shot noise
    depth_factors = [0.25, 0.5, 1.0, 2.0, 4.0]
    print(f"\n--- must using count (depth_factors): {depth_factors} ---")

    n_cells, n_genes = original_data.shape
    base_filename = os.path.splitext(os.path.basename(file_path))[0]

    # 4. Loop over depth factors and generate Poisson-resampled datasets
    for depth in depth_factors:
        print(f"\n========== Processing noiselevel : depth factor = {depth} ==========")

        # Expected counts matrix λ_ij under this sequencing depth
        lam = original_data * depth

        # Avoid numerical problems: enforce non-negativity
        lam = np.maximum(lam, 0.0)

        print("--- based oncurrent λ matrixfrom Poisson counts ---")
        noisy_counts = np.random.poisson(lam=lam).astype(np.float32)

        # Construct new AnnData object
        adata_noisy = anndata.AnnData(
            noisy_counts,
            obs=adata_original.obs.copy(),
            var=adata_original.var.copy()
        )

        # Record metadata
        adata_noisy.uns["technoise_model"] = "Poisson_resampling"
        adata_noisy.uns["technoise_depth_factor"] = float(depth)
        adata_noisy.uns["technoise_note"] = (
            "Counts generated by Poisson resampling with λ_ij = depth * original_ij "
            "to simulate sequencing shot noise."
        )

        # Save to new h5ad file
        output_filename = f"{base_filename}_poisson_depth_{depth}.h5ad"
        output_path = os.path.join(output_dir, output_filename)
        print(f"Saving to: {output_path}")
        adata_noisy.write_h5ad(output_path)

    print("\n--- allbased on Poisson noise data ! ---")


if __name__ == "__main__":
    # Example usage: you can adapt these paths to your environment
    input_file = "/share/PertBench/data/fig1/raw_task1/task1_train_CD4T_exp.h5ad"

    # When the original file does not exist, create a dummy dataset for testing
    if not os.path.exists(input_file):
        print(f" found '{input_file}'.Creating for testing h5ad file...")
        n_obs, n_vars = 100, 500
        # Use Poisson-distributed dummy counts as a realistic starting point
        X_dummy = np.random.poisson(lam=5.0, size=(n_obs, n_vars)).astype(np.float32)
        dummy_adata = anndata.AnnData(X_dummy)
        dummy_adata.write(input_file)
        print(f" file '{input_file}'.")

    output_directory = "/share/PertBench/data/add_poisson_technoise_output"

    generate_poisson_technoise_files(input_file, output_directory)
