model:
  ae:
    input_dim: 6998
    latent_dim: 256
    hidden_dim: 1024
  diffusion:
    timesteps: 1000
    beta_1: 1e-4
    beta_T: 0.02
    hidden_dim: 512

data:
  path: ./dataset/scrna_data/scrna.h5ad
  batch_size: 32
  label_key: Condition
  num_workers: 4

train:
  batch_size: 2048
  device: cuda
  epoch: 1000
  lr: 1e-5
  weight_decay: 1.0e-4
  grad_clip: 0.5
  warmup_multiplier: 10
  save_weight_dir: /data/ppnm/checkpoints/PertDiffBench/checkpoints/sweep/fig2_unseen_cd4t/ddpm_mlp__lr__1e-5/run1
  resume_from: null
  num_workers: 32
  ckpt_save_interval: 500

sample:
  batch_size: 64
  sampled_dir: /data/ppnm/data/PertDiffBench/samples/sweep/fig2_unseen_cd4t/ddpm_mlp__lr__1e-5/run1
  out_h5ad: synthetic_ddpm_mlp__lr__1e-5.h5ad
